// ============================================================
// IC Agent Configuration & Actor Construction
// ============================================================
//
// Handles:
// - Environment detection (local vs mainnet)
// - Agent creation with correct host
// - Actor creation for known canisters (factory, board)
// - Dynamic actor creation for profile canisters

import { HttpAgent, Actor, type Identity } from "@dfinity/agent";
import { Principal } from "@dfinity/principal";
import { idlFactory as factoryIdl } from "./factory.did";
import { idlFactory as profileIdl } from "./profile.did";

// Environment config — injected by vite-plugin-environment from .env
const DFX_NETWORK = process.env.DFX_NETWORK || "local";
export const isLocal = DFX_NETWORK === "local";

const host = isLocal ? "http://127.0.0.1:4943" : "https://icp-api.io";

// Canister IDs — injected from .env (generated by dfx)
const FACTORY_CANISTER_ID = process.env.CANISTER_ID_PROFILE_FACTORY || "";
const BOARD_CANISTER_ID = process.env.CANISTER_ID_BULLETIN_BOARD || "";

export const II_URL = isLocal
  ? `http://${process.env.CANISTER_ID_INTERNET_IDENTITY}.localhost:4943`
  : "https://identity.ic0.app";

// ============================================================
// Agent creation
// ============================================================

let _agent: HttpAgent | null = null;

export async function createAgent(identity: Identity): Promise<HttpAgent> {
  const agent = await HttpAgent.create({ host, identity });

  // CRITICAL: fetch root key on local replica only.
  // On mainnet this would be a security vulnerability.
  if (isLocal) {
    await agent.fetchRootKey();
  }

  _agent = agent;
  return agent;
}

export function getAgent(): HttpAgent | null {
  return _agent;
}

// ============================================================
// Actor factories
// ============================================================

export function createFactoryActor(agent: HttpAgent) {
  return Actor.createActor(factoryIdl, {
    agent,
    canisterId: FACTORY_CANISTER_ID,
  });
}

export function createProfileActor(agent: HttpAgent, canisterId: string | Principal) {
  return Actor.createActor(profileIdl, {
    agent,
    canisterId: typeof canisterId === "string" ? canisterId : canisterId.toText(),
  });
}

// ============================================================
// Type helpers for Candid Result variants
// ============================================================

export type CandidResult<T> = { Ok: T } | { Err: CandidError };
export type CandidError = {
  [key: string]: { message: string };
};

export function isOk<T>(result: CandidResult<T>): result is { Ok: T } {
  return "Ok" in result;
}

export function getError(result: CandidResult<unknown>): string {
  if ("Err" in result) {
    const err = result.Err;
    const variant = Object.keys(err)[0];
    const msg = (err as any)[variant]?.message || "Unknown error";
    return `${variant}: ${msg}`;
  }
  return "Unknown error";
}
