[source."git+https://github.com/Together-Alone-Ventures/ICP-Delete-Leaf.git?rev=2a10bf3ee056d3ff53327ca23654609a6f430c5e"]
git = "https://github.com/Together-Alone-Ventures/ICP-Delete-Leaf.git"
rev = "2a10bf3ee056d3ff53327ca23654609a6f430c5e"
replace-with = "vendored-sources"

[source."git+https://github.com/Together-Alone-Ventures/zombie-core?rev=223723885cfbb548d6b218aee8500b073fda4b58"]
git = "https://github.com/Together-Alone-Ventures/zombie-core"
rev = "223723885cfbb548d6b218aee8500b073fda4b58"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
