[source."git+https://github.com/Together-Alone-Ventures/ICP-Delete-Leaf.git?rev=8e5024dc8d27be19dafc579b2ac955e45da28b0c"]
git = "https://github.com/Together-Alone-Ventures/ICP-Delete-Leaf.git"
rev = "8e5024dc8d27be19dafc579b2ac955e45da28b0c"
replace-with = "vendored-sources"

[source."git+https://github.com/Together-Alone-Ventures/zombie-core?rev=8ac64df5d0110ec7ebbbe8382b7a826dda17085a"]
git = "https://github.com/Together-Alone-Ventures/zombie-core"
rev = "8ac64df5d0110ec7ebbbe8382b7a826dda17085a"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
