import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import environment from "vite-plugin-environment";
import dotenv from "dotenv";
import { resolve } from "path";

// Load the .env file generated by dfx (contains canister IDs)
dotenv.config({ path: resolve(__dirname, "../../.env") });

export default defineConfig({
  plugins: [
    react(),
    // Inject canister IDs and network config as environment variables
    environment({
      CANISTER_ID_BULLETIN_BOARD: "",
      CANISTER_ID_PROFILE_FACTORY: "",
      CANISTER_ID_INTERNET_IDENTITY: "",
      DFX_NETWORK: "",
      // F3 deployment placeholder: public zd-finalizer-service origin, no trailing slash.
      FINALIZER_BASE_URL: "",
    }),
  ],
  build: {
    outDir: "dist",
    emptyOutDir: true,
  },
  server: {
    // Proxy API calls to the local replica during development
    proxy: {
      "/api": {
        target: "http://127.0.0.1:4943",
        changeOrigin: true,
      },
    },
  },
  define: {
    // Required for @dfinity/agent to work in browser
    "process.env.NODE_ENV": JSON.stringify(
      process.env.NODE_ENV || "development"
    ),
  },
  optimizeDeps: {
    esbuildOptions: {
      // Node.js global to browser globalThis
      define: {
        global: "globalThis",
      },
    },
  },
});
